[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Upload settings
upload_speed = 1500000
monitor_speed = 115200

; Library dependencies
lib_deps = 
    M5Unified
    fastled/FastLED@^3.6.0
    sensirion/Sensirion I2C SCD4x@^0.4.0
    handmade0octopus/ESP32-TWAI-CAN@^1.0.1

; Filesystem settings
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv
